services:
  blobstore:
    build:
      context: ./dev/blobstore
      dockerfile: Dockerfile
    environment:
      MINIO_ROOT_USER: "username"
      MINIO_ROOT_PASSWORD: "password"
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - ./dev/minio/data:/data
    command: server /data --console-address ":9001"

  wiemancdn:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    environment:
      S3_ENDPOINT: "http://blobstore:9000"
      ACCESS_KEY_ID: "username"
      SECRET_ACCESS_KEY: "password"
      BUCKET_NAME: "test-bucket"
      REGION: "s-east-1"