name: Test

on:
  pull_request:
    branches:
      - master

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout
          uses: actions/checkout@v4

        - name: Set up Go
          uses: actions/setup-go@v5
          with:
            go-version: '1.23.1'

        - name: Run tests
          run: make test

        - name: Build Docker image
          run: docker build -t wiemanimages .
